config/routes.rb
Rails.application.routes.draw do
  resources :entries
  get 'welcome/index'
  root "welcome#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
    @entries = Entry.all.order(updated_at: "desc")
  end

  def show
    @entry = Entry.find(params[:id])
  end
  def new
    @entry = Entry.new
  end

  def create
    puts "ENTRY: #{create_params.inspect}"

    @entry = Entry.create(create_params)
    redirect_to entry_path(@entry)
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.delete
    redirect_to entries_path
  end

  def edit
    @entry = Entry.find(params[:id])
    render :new
  end

  def update
    @entry = Entry.find(params[:id])
    @entry.update_attributes(create_params)
    redirect_to entry_path(@entry)
  end
  
  private

    def create_params
      params[:entry].permit("title", "contents", "date")
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @entries = Entry.all.order(updated_at: "desc")
		@website = [
			["http://tryruby.org/levels/4/challenges/3", "Try Ruby"],
			["http://wuaki.tv", "Where I spend 80% of my life"],
			["http://twitter.com/sara_doe", "Where I tell my life to strangers"],
			["http://instagram.com/sara_doe", "Where I SPAM everyone with pics of my cat"]
		]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/_entry.html.erb
<b><%= link_to(entry.title, entry_path(entry)) %></b>
<p><i><%= entry.date %></i></p>
<p><%= entry.contents %></p>
<p><%= button_to("delete", entry, method: :delete) %></p>
<p><%= link_to("update", edit_entry_path(entry)) %></p>

app/views/entries/index.html.erb
<% for entry in @entries %>
  <%= render entry %>
<% end %>
<%= link_to("new entry", new_entry_path) %>

app/views/entries/new.html.erb
<%= form_for(@entry) do |form| %>

	<div class="field">
		<p><%= form.label("title") %></p>
		<p><%= form.text_field("title") %></p>
	</div>

	<p><%= form.label("contents") %></p>
	<p><%= form.text_area("contents") %></p>

	<p><%= form.label("date") %></p>
	<p><%= form.date_field("date") %></p>

	<p><%= form.submit("You're done!") %></p>

<% end %>

app/views/entries/show.html.erb
<h1>Ruby is no longer just a song I like</h1>

<%=render @entry %>

<%= link_to("Back to list", entries_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>
	More often that you'd wish
</h1>
		<% for entry in @entries %>
        <b><%=entry.title%></b>
        <p><i><%=entry.date%></i></p>
        <p><%=entry.contents%></p>
    <% end %>
		<% for url, name in @website %>
		    <li> <a href=<%= url %>> <%= name %></a> </li>
		<% end %>

		<img src="https://scontent-mad.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/10801644_10204568644551846_4155399223848972380_n.jpg?oh=15ef58c36d11d8a32c6a476324e10609&oe=55A7B70D" style="width:200px" />